apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-u5tg
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xfdy-tenant/rhtap-demo-app/hacbs-test-project-u5tg@sha256:5397db50dd4247bda2034a81945f34b6506897023022717a065a4fa509b30ed2
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
