apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-u5tg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-u5tg
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-u5tg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-u5tg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-u5tg
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xfdy-tenant/rhtap-demo-app/hacbs-test-project-u5tg@sha256:403d6938e247f041d396715c537b11ab1e2d150212e5ba253c955f901c27de86
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
